#!/bin/zsh
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey "^p" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey -r "^u"
bindkey -r "^d"
# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line

# Key bindings
